# Generated by Django 4.2.4 on 2023-08-29 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.CharField(default='Auto', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='display_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.CharField(default='Auto', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='void',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=1),
        ),
    ]
