# Generated by Django 4.2.4 on 2023-08-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_alter_product_options_product_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_pic',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
